# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
[┌ ](surface0)\
$all$fill $cmd_duration$time
[└─](surface0)$character\
"""

# Inserts a blank line between shell prompts
add_newline = true

# Specify palette used for color names
palette = "ayu_mirage"

[palettes.ayu_mirage]
cyan = "#5CCFE6"
yellow = "#FFD173"
blue = "#73D0FF"
green = "#D5FF80"
teal = "#95E6CB"
red = "#F28779"
orange = "#FFAD66"
purple = "#DFBFFF"
text = "#CCCAC2"
subtext = "#6B7A8B"
surface0 = "#4A505A"

[fill]
symbol = "-"
style = "surface0"

[line_break]
disabled = true

[time]
disabled = false

[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:yellow)"
vimcmd_visual_symbol = "[❮](bold fg:blue)"
vimcmd_replace_symbol = "[❮](bold fg:purple)"
vimcmd_replace_one_symbol = "[❮](bold fg:purple)"

[username]
style_user = "bold fg:yellow"
style_root = "bold fg:red"

[hostname]
style = "bold fg:blue"
ssh_symbol = " "

[directory]
style = "bold fg:teal"
read_only = " 󰌾"
truncation_symbol = "󰇘/"

[git_branch]
style = "bold fg:purple"
symbol = " "
format = "on [$symbol$branch ]($style)"

[git_commit]
tag_symbol = "  "

[git_status]
style = "fg:red"
format = "$modified$deleted$untracked$ahead_behind "
modified = "[ ](fg:yellow)"
deleted = "[ ](fg:red)"
renamed = "[ ](fg:yellow)"
stashed = "[ ](fg:teal)"
conflicted = "[ ](fg:red) "
untracked = "[ ](fg:orange)"
ahead = "[ ](fg:blue)"
behind = "[ ](fg:blue)"
up_to_date = "[ ](fg:green)"

[package]
symbol = "󰏗 "

[docker_context]
symbol = " "

[conda]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[zig]
symbol = " "
